module.exports = {
  expense1: {
    amount_cents: 60784,
    date: '2018-01-21',
    description: 'Jean shorts forage taiyaki twee, authentic cornhole pinterest cardigan echo park raw denim franzen trust fund readymade.',
    reimbursed_cents: 291,
  },
  expense2: {
    amount_cents: 49592,
    date: '2018-01-27',
    description: 'Pok pok sartorial twee, slow-carb put a bird on it DIY narwhal.',
    reimbursed_cents: 41,
  },
  expense3: {
    amount_cents: 91995,
    date: '2018-02-23',
    description: 'Hot chicken master cleanse pop-up everyday carry pickled bitters raclette portland williamsburg cardigan fanny pack 90\'s adaptogen dreamcatcher beard.',
    reimbursed_cents: 867,
  },
  expense4: {
    amount_cents: 21936,
    date: '2018-03-03',
    description: 'Mixtape whatever hashtag skateboard.',
    reimbursed_cents: 578,
  },
  expense5: {
    amount_cents: 88378,
    date: '2018-03-05',
    description: 'Blue bottle flexitarian af trust fund, mustache banjo retro cornhole authentic fashion axe normcore.',
    reimbursed_cents: 54,
  },
  expense6: {
    amount_cents: 71624,
    date: '2018-03-07',
    description: 'Fingerstache vegan beard craft beer aesthetic seitan.',
    reimbursed_cents: 477,
  },
  expense7: {
    amount_cents: 71848,
    date: '2018-03-24',
    description: 'Fanny pack four loko green juice cloud bread, letterpress banh mi chicharrones pinterest cray tbh cornhole glossier ennui narwhal.',
    reimbursed_cents: 472,
  },
  expense8: {
    amount_cents: 28526,
    date: '2018-03-28',
    description: 'Locavore pork belly +1 enamel pin venmo, plaid neutra slow-carb.',
    reimbursed_cents: 782,
  },
  expense9: {
    amount_cents: 66477,
    date: '2018-03-29',
    description: ' Deep v disrupt hexagon, messenger bag master cleanse chia blue bottle marfa next level leggings hoodie lo-fi crucifix irony williamsburg.',
    reimbursed_cents: 162,
  },
  expense10: {
    amount_cents: 89108,
    date: '2018-03-30',
    description: 'Selfies kitsch cold-pressed meggings iPhone you probably haven\'t heard of them enamel pin pitchfork.',
    reimbursed_cents: 385,
  },
  expense11: {
    amount_cents: 66168,
    date: '2018-04-10',
    description: ' Church-key kombucha stumptown taiyaki raclette tacos.',
    reimbursed_cents: 158,
  },
  expense12: {
    amount_cents: 3634,
    date: '2018-04-29',
    description: 'Adaptogen post-ironic gastropub drinking vinegar, whatever pickled cold-pressed helvetica dreamcatcher fanny pack.',
    reimbursed_cents: 338,
  },
  expense13: {
    amount_cents: 65825,
    date: '2018-05-20',
    description: 'Dreamcatcher godard messenger bag pok pok, sartorial intelligentsia paleo taiyaki.',
    reimbursed_cents: 116,
  },
  expense14: {
    amount_cents: 60830,
    date: '2018-06-16',
    description: 'Street art DIY godard, wolf next level 90\'s schlitz.',
    reimbursed_cents: 582,
  },
  expense15: {
    amount_cents: 52114,
    date: '2018-06-17',
    description: 'Poke kombucha chartreuse butcher occupy keffiyeh drinking vinegar celiac.',
    reimbursed_cents: 798,
  },
  expense16: {
    amount_cents: 75206,
    date: '2018-07-01',
    description: 'Prism irony church-key lumbersexual echo park hashtag locavore sriracha offal swag.',
    reimbursed_cents: 288,
  },
  expense17: {
    amount_cents: 7716,
    date: '2018-07-08',
    description: 'Vegan bespoke portland, squid vaporware la croix enamel pin taiyaki before they sold out umami chicharrones shoreditch blog.',
    reimbursed_cents: 573,
  },
  expense18: {
    amount_cents: 66929,
    date: '2018-07-28',
    description: 'Celiac vinyl glossier umami.',
    reimbursed_cents: 322,
  },
  expense19: {
    amount_cents: 44220,
    date: '2018-08-15',
    description: 'Stumptown taxidermy small batch waistcoat marfa franzen vice, hexagon copper mug umami YOLO keffiyeh brunch.',
    reimbursed_cents: 43,
  },
  expense20: {
    amount_cents: 18032,
    date: '2018-08-25',
    description: 'Tote bag echo park twee hammock organic, kitsch direct trade master cleanse pok pok health goth salvia dreamcatcher chicharrones chambray.',
    reimbursed_cents: 581,
  },
  expense21: {
    amount_cents: 28640,
    date: '2018-09-07',
    description: 'Air plant echo park poutine, pitchfork listicle freegan tbh.',
    reimbursed_cents: 481,
  },
  expense22: {
    amount_cents: 60593,
    date: '2018-10-01',
    description: 'Farm-to-table hammock try-hard godard kogi health goth pug vexillologist taxidermy literally selvage wayfarers poutine green juice banjo.',
    reimbursed_cents: 927,
  },
  expense23: {
    amount_cents: 88322,
    date: '2018-10-08',
    description: 'Truffaut put a bird on it iPhone biodiesel selfies kinfolk poke vegan chia church-key hammock letterpress.',
    reimbursed_cents: 533,
  },
  expense24: {
    amount_cents: 65457,
    date: '2018-10-13',
    description: 'Semiotics chambray subway tile brooklyn live-edge iceland cornhole heirloom truffaut beard succulents ennui craft beer kickstarter.',
    reimbursed_cents: 937,
  },
  expense25: {
    amount_cents: 90704,
    date: '2018-10-18',
    description: 'Af cardigan godard flannel coloring book.',
    reimbursed_cents: 841,
  },
  expense26: {
    amount_cents: 84248,
    date: '2018-10-20',
    description: 'Banjo jean shorts celiac, vice neutra man braid umami taxidermy vexillologist mixtape meh semiotics snackwave put a bird on it.',
    reimbursed_cents: 929,
  },
  expense27: {
    amount_cents: 49096,
    date: '2018-10-28',
    description: 'Pitchfork marfa put a bird on it, lomo synth yr mixtape unicorn kinfolk prism migas.',
    reimbursed_cents: 458,
  },
  expense28: {
    amount_cents: 67056,
    date: '2018-12-21',
    description: 'Forage tumeric street art keffiyeh butcher.',
    reimbursed_cents: 516,
  },
  expense29: {
    amount_cents: 90391,
    date: '2018-12-21',
    description: 'Raw denim irony cronut vexillologist semiotics synth vinyl.',
    reimbursed_cents: 585,
  },
  expense30: {
    amount_cents: 39792,
    date: '2018-12-29',
    description: 'Aesthetic helvetica leggings sustainable pitchfork.',
    reimbursed_cents: 154,
  },
};
