module.exports = {
  user1: {
    email: 'LindsayRigby@example.com',
    firstName: 'Lindsay',
    lastName: 'Rigby',
    middleName: 'Adella',
    password: 's8aG3th3k+tHuzaC',
  },
  user2: {
    email: 'LaceyWalters@example.com',
    firstName: 'Lacey',
    lastName: 'Walters',
    middleName: 'Lessie',
    password: 'k?TratrEpU?5Udru',
  },
  user3: {
    email: 'freddiesanford@example.com',
    firstName: 'Freddie',
    lastName: 'Sanford',
    middleName: 'Rick',
    password: 'WEHe$eT3a86wa@$P',
  },
  user4: {
    email: 'codysimonson@example.com',
    firstName: 'Cody',
    lastName: 'Simonson',
    middleName: 'Earline',
    password: 'Pus3=stazA3uh7j&',
  },
  user5: {
    email: 'sandygardener@example.com',
    firstName: 'Sandy',
    lastName: 'Gardener',
    middleName: 'Therese',
    password: 'se3Rak_Thuvafes5',
  },
  user6: {
    email: 'devonspeight@example.com',
    firstName: 'Devon',
    lastName: 'Speight',
    middleName: 'Oliver',
    password: 'D?=Mu*AsTU7umud6',
  },
  user7: {
    email: 'robbiedickman@example.com',
    firstName: 'Robbie',
    lastName: 'Dickman',
    middleName: 'Tyler',
    password: 'cRUk5M$kaFrEdrev',
  },
  user8: {
    email: 'olliesummers@example.com',
    firstName: 'Ollie',
    lastName: 'Summers',
    middleName: 'Brandon',
    password: 'z8sU3tEfRe2+cREc',
  },
  user9: {
    email: 'kerrydickenson@example.com',
    firstName: 'Kerry',
    lastName: 'Dickenson',
    middleName: 'Richard',
    password: 'st!dRETr4b6fuheb',
  },
  user10: {
    email: 'chrissudworth@example.com',
    firstName: 'Chris',
    lastName: 'Sudworth',
    middleName: 'David',
    password: 'kaDRe-hEPhetH72r',
  },
  user11: {
    email: 'duanerice@example.com',
    firstName: 'Duane',
    lastName: 'Rice',
    middleName: 'Zachary',
    password: 'P&Txc#2%!4SL$@#a',
  },
  user12: {
    email: 'jacobmccoy@example.com',
    firstName: 'Jacob',
    lastName: 'Mccoy',
    middleName: 'Warren',
    password: 'UMyc=t_4C9%3d&vm',
  },
  user13: {
    email: 'patriciafox@example.com',
    firstName: 'Patricia',
    lastName: 'Fox',
    middleName: 'Dora',
    password: 'B-78-Tx+7&*m$dXe',
  },
  user14: {
    email: 'drewreeves@example.com',
    firstName: 'Drew',
    lastName: 'Reeves',
    middleName: 'Randal',
    password: '@pBJU*umf!bS-4mv',
  },
  user15: {
    email: 'joannyoung@example.com',
    firstName: 'Joann',
    lastName: 'Young',
    middleName: 'Dwayne',
    password: '$DJ5veS?UM&8Bf@+',
  },
  user16: {
    email: 'luispena@example.com',
    firstName: 'Luis',
    lastName: 'Pena',
    middleName: 'Ramona',
    password: 'SycUzp6Y%nBBMJ3$',
  },
  user17: {
    email: 'matthewdiaz@example.com',
    firstName: 'Matthew',
    lastName: 'Diaz',
    middleName: 'Laurence',
    password: '5-_h%kp+3AvLB48*',
  },
  user18: {
    email: 'carmenrose@example.com',
    firstName: 'Carmen',
    lastName: 'Rose',
    middleName: 'Doyle',
    password: 'Yweay5cmxN-39=p6',
  },
  user19: {
    email: 'carriesanders@example.com',
    firstName: 'Carrie',
    lastName: 'Sanders',
    middleName: 'Christian',
    password: 'yBUY8*S%8bWJmbh=',
  },
  user20: {
    email: 'javierbarrett@example.com',
    firstName: 'Javier',
    lastName: 'Barrett',
    middleName: 'Sherry',
    password: '3bFvdQC6?jcUD3&a',
  },
  user21: {
    email: 'louisegreen@example.com',
    firstName: 'Louise',
    lastName: 'Green',
    middleName: 'Betty',
    password: 'La+f3J3sV98J3-9s',
  },
  user22: {
    email: 'darrelllewis@example.com',
    firstName: 'Darrell',
    lastName: 'Lewis',
    middleName: 'Eva',
    password: 'GKTWTP%vWW2VRchL',
  },
  user23: {
    email: 'lynnmclaughlin@example.com',
    firstName: 'Lynn',
    lastName: 'Mclaughlin',
    middleName: 'Willard',
    password: '+dqh?8*yUezzrHQ7',
  },
  user24: {
    email: 'hoperose@example.com',
    firstName: 'Hope',
    lastName: 'Rose',
    middleName: 'Kathleen',
    password: '+P@9AwhVFNL+&Vfz',
  },
  user25: {
    email: 'loranichols@example.com',
    firstName: 'Lora',
    lastName: 'Nichols',
    middleName: 'Jill',
    password: '4@Q%Z94-#d=hgc_L',
  },
  user26: {
    email: 'jillcook@example.com',
    firstName: 'Jill',
    lastName: 'Cook',
    middleName: 'Lynn',
    password: '@Kc7@Eba3vVF8_KR',
  },
  user27: {
    email: 'rodneyalvarado@example.com',
    firstName: 'Rodney',
    lastName: 'Alvarado',
    middleName: 'Rene',
    password: 'mAcTJVc6_3zBr2Zw',
  },
  user28: {
    email: 'elijahlyons@example.com',
    firstName: 'Elijah',
    lastName: 'Lyons',
    middleName: 'Dorothy',
    password: '4X$$j@EE-LT=teh+',
  },
  user29: {
    email: 'sandraflores@example.com',
    firstName: 'Sandra',
    lastName: 'Flores',
    middleName: 'Candice',
    password: 'ujgAJ7a4xgP*P&EJ',
  },
  user30: {
    email: 'rachaelfleming@example.com',
    firstName: 'Rachael',
    lastName: 'Fleming',
    middleName: 'Josefina',
    password: 'qPJ%3sLzyNKek4EZ',
  },
  invalid1: { // No email
    email: '',
    firstName: 'Harper',
    lastName: 'Westbrook',
    middleName: 'Spencer',
    password: 'r2=6prusP&NaR7p?',
  },
  invalid2: { // No first name
    email: 'bernynorman@example.com',
    firstName: '',
    lastName: 'Norman',
    middleName: 'Hiro',
    password: 'b2wePRura_3S3uBu',
  },
  invalid3: { // No last name
    email: 'lindsaybrooks@example.com',
    firstName: 'Lindsay',
    lastName: '',
    middleName: 'George',
    password: '6etrudAnu7af#@=2',
  },
  invalid4: { // No password
    email: 'dariandannel@example.com',
    firstName: 'Darian',
    lastName: 'Dannel',
    middleName: 'Jack',
    password: '',
  },
  invalid5: { // Invalid email
    email: 'lindsayhansonexample.com',
    firstName: 'Lindsay',
    lastName: 'Hanson',
    middleName: 'Tom',
    password: 'QU?E$reV4ch@P2cu',
  },
  invalid6: { // Password too short
    email: 'shannoncarman@example.com',
    firstName: 'Shannon',
    lastName: 'Carman',
    middleName: 'Adelaide',
    password: 'Z$nu8pU',
  },
};
